# Generated by Django 5.2.10 on 2026-02-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='time_slot',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
