# Generated by Django 5.2.11 on 2026-02-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_block_classroom_facultyprofile_courseoffering'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='has_projector',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classroom',
            name='room_type',
            field=models.CharField(choices=[('classroom', 'Classroom'), ('lab', 'Lab'), ('seminar', 'Seminar'), ('auditorium', 'Auditorium')], default='classroom', max_length=16),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='academic_year',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='expected_strength',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='mode',
            field=models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='offline', max_length=16),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='section',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='department',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='max_weekly_load',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
