# Generated by Django 5.2.11 on 2026-02-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_block_notes_classroom_floor_classroom_has_projector_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="department",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="student",
            name="semester",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="semester",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
