# Generated by Django 5.2.11 on 2026-02-20 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_student_year_sem_department_and_course_year_sem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=32, unique=True)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("semester", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="section",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="students", to="attendance.section"),
        ),
    ]
