# Generated by Django 5.2.11 on 2026-02-21 11:38

import django.db.models.deletion
from django.db import migrations, models


def migrate_section_names_to_fk(apps, schema_editor):
    """Try to match old section names to Section objects."""
    CourseOffering = apps.get_model('attendance', 'CourseOffering')
    Section = apps.get_model('attendance', 'Section')
    
    # Build a map of section names to Section objects
    section_map = {}
    for s in Section.objects.all():
        section_map[s.name] = s
    
    # For each offering with an old section value, try to match to a Section
    for offering in CourseOffering.objects.all():
        old_value = offering._old_section or ''
        if old_value and old_value in section_map:
            offering.section = section_map[old_value]
            offering.save(update_fields=['section'])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('attendance', '0008_section_and_student_section'),
    ]

    operations = [
        # Add course field to Section
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='attendance.course'),
        ),
        
        # Add enrolled_courses to Student
        migrations.AddField(
            model_name='student',
            name='enrolled_courses',
            field=models.ManyToManyField(related_name='enrolled_students', through='attendance.Enrollment', to='attendance.course'),
        ),
        
        # Rename old section field to preserve data temporarily
        migrations.RenameField(
            model_name='courseoffering',
            old_name='section',
            new_name='_old_section',
        ),
        
        # Add new section field as ForeignKey
        migrations.AddField(
            model_name='courseoffering',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='attendance.section'),
        ),
        
        # Migrate data from old field to new field
        migrations.RunPython(migrate_section_names_to_fk, reverse_code=migrations.RunPython.noop),
        
        # Remove old section field
        migrations.RemoveField(
            model_name='courseoffering',
            name='_old_section',
        ),
        
        # Update course field to CASCADE
        migrations.AlterField(
            model_name='courseoffering',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='attendance.course'),
        ),
        
        # Update ordering
        migrations.AlterModelOptions(
            name='courseoffering',
            options={'ordering': ['course__code', 'section__name']},
        ),
        
        # Update unique constraint
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together={('course', 'section', 'faculty')},
        ),
    ]
