# Generated by Django 5.2.11 on 2026-02-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_section_course_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoffering',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='expected_strength',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='start_time',
        ),
    ]
