# Generated by Django 5.2.11 on 2026-02-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_remove_courseoffering_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together={('course', 'section')},
        ),
    ]
