# Generated by Django 5.2.11 on 2026-02-21 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_section_course_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parent_phone',
            new_name='student_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.CreateModel(
            name='StudentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_sections', to='attendance.section')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_mapping', to='attendance.student')),
            ],
            options={
                'ordering': ['section__name', 'student__registration_number'],
                'unique_together': {('student', 'section')},
            },
        ),
    ]
