# Generated by Django 5.2.11 on 2026-02-21 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_rename_parent_phone_student_student_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('time_slot', models.CharField(choices=[('8am-9am', '8 a.m. - 9 a.m.'), ('9am-10am', '9 a.m. - 10 a.m.'), ('10am-11am', '10 a.m. - 11 a.m.'), ('11am-12pm', '11 a.m. - noon'), ('12pm-1pm', 'noon - 1 p.m.'), ('1pm-2pm', '1 p.m. - 2 p.m.'), ('2pm-3pm', '2 p.m. - 3 p.m.'), ('3pm-4pm', '3 p.m. - 4 p.m.'), ('4pm-5pm', '4 p.m. - 5 p.m.'), ('5pm-6pm', '5 p.m. - 6 p.m.'), ('6pm-7pm', '6 p.m. - 7 p.m.'), ('7pm-8pm', '7 p.m. - 8 p.m.'), ('8pm-9pm', '8 p.m. - 9 p.m.'), ('9pm-10pm', '9 p.m. - 10 p.m.')], default='8am-9am', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='attendance.classroom')),
                ('section_course_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='attendance.sectioncoursefaculty')),
            ],
            options={
                'ordering': ['day_of_week', 'time_slot', 'classroom__block__code', 'classroom__room_number'],
                'constraints': [models.UniqueConstraint(fields=('classroom', 'day_of_week', 'time_slot'), name='unique_room_slot', violation_error_message='This classroom is already booked for this time slot.')],
            },
        ),
    ]
