# Generated by Django 5.2.11 on 2026-02-22 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_schedule_course_offering_schedule_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeUpClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('8am-9am', '8 a.m. - 9 a.m.'), ('9am-10am', '9 a.m. - 10 a.m.'), ('10am-11am', '10 a.m. - 11 a.m.'), ('11am-12pm', '11 a.m. - noon'), ('12pm-1pm', 'noon - 1 p.m.'), ('1pm-2pm', '1 p.m. - 2 p.m.'), ('2pm-3pm', '2 p.m. - 3 p.m.'), ('3pm-4pm', '3 p.m. - 4 p.m.'), ('4pm-5pm', '4 p.m. - 5 p.m.'), ('5pm-6pm', '5 p.m. - 6 p.m.'), ('6pm-7pm', '6 p.m. - 7 p.m.'), ('7pm-8pm', '7 p.m. - 8 p.m.'), ('8pm-9pm', '8 p.m. - 9 p.m.'), ('9pm-10pm', '9 p.m. - 10 p.m.')], max_length=20)),
                ('remedial_code', models.CharField(max_length=8, unique=True)),
                ('reason', models.TextField(help_text='Reason for make-up class')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='makeup_classes', to='attendance.classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeup_classes', to='attendance.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeup_classes', to='attendance.facultyprofile')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeup_classes', to='attendance.section')),
            ],
            options={
                'ordering': ['-session_date', 'time_slot'],
            },
        ),
        migrations.CreateModel(
            name='MakeUpAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=16)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
                ('makeup_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.makeupclass')),
            ],
            options={
                'unique_together': {('makeup_class', 'student')},
            },
        ),
    ]
