# Generated by Django 5.2.11 on 2026-02-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_makeupclass_makeupattendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeupattendancerecord',
            name='marked_via',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('student', 'Student (Self)'), ('auto', 'Auto-marked')], default='faculty', max_length=16),
        ),
    ]
