# Generated by Django 5.2.11 on 2026-02-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_student_and_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='location',
            field=models.CharField(default='Campus Center', max_length=128),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='stall_name',
            field=models.CharField(default='Main Canteen', max_length=128),
        ),
    ]
