# Generated by Django 5.2.11 on 2026-02-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_fooditem_location_fooditem_stall_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='category',
            field=models.CharField(default='All Items', max_length=64),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
