# Generated by Django 5.2.11 on 2026-02-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_fooditem_category_fooditem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preorder',
            name='verification_token',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
