# Generated by Django 5.2.11 on 2026-02-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_preorder_email_sent_preorder_verification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorder',
            name='verification_token',
        ),
        migrations.AddField(
            model_name='preorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='preorder',
            name='penalty_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('collected', 'Collected'), ('missed', 'Missed')], default='pending', max_length=16),
        ),
    ]
