# Generated by Django 5.2.11 on 2026-02-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_emergencyalert_bulkorder_loyaltypoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkorder',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
