# Generated by Django 5.2.11 on 2026-02-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_bulkorder_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='packaging_option',
            field=models.CharField(choices=[('eat', 'Eat there only'), ('parcel', 'Pack for parcel')], default='eat', max_length=8),
        ),
    ]
