# Generated by Django 5.2.11 on 2026-02-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_preorder_packaging_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltypoints',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loyaltypoints',
            name='favorite_stall',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='loyaltypoints',
            name='favorite_stall_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loyaltypoints',
            name='first_order_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loyaltypoints',
            name='last_order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loyaltypoints',
            name='weekly_first_order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loyaltypoints',
            name='weekly_orders_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
