# Generated by Django 5.2.11 on 2026-02-12 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '014_fooditem_stall_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stall',
            options={},
        ),
        migrations.RemoveField(
            model_name='stall',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='stall',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='stall',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='stall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.stall'),
        ),
        migrations.AlterField(
            model_name='stall',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stall',
            name='location',
            field=models.CharField(default='Campus Center', max_length=128),
        ),
        migrations.AlterField(
            model_name='stall',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='StallOwner',
        ),
    ]
