# Generated by Django 5.2.11 on 2026-02-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_recreate_stallowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkorder',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='submitted', max_length=16),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='packaging_option',
            field=models.CharField(choices=[('eat', 'Dine-in'), ('parcel', 'Pack for parcel')], default='eat', max_length=8),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cooking', 'Cooking'), ('ready', 'Ready'), ('collected', 'Collected'), ('missed', 'Missed')], default='pending', max_length=16),
        ),
    ]
